version: '3'
networks:
  one-app-at-test-network: null
services:
  one-app:
    build: ../
    image: 'one-app:at-test'
    volumes:
      - './one-app/one-app-cert.pem:/opt/cert.pem'
      - './one-app/one-app-privkey.pem:/opt/key.pem'
      - './nginx/nginx-cert.pem:/opt/nginx-cert.pem'
      - './extra-certs.pem:/opt/extra-certs.pem'
    env_file:
      - ./one-app/base.env
    networks:
      one-app-at-test-network: null
    depends_on:
      - fast-api
      - slow-api
      - extra-slow-api
      - nginx
    entrypoint: sh -c 'sleep 2s && node lib/server'
    ports:
      - '27180:8443'
  fast-api:
    build: ./api
    ports:
      - '8000:80'
    networks:
      one-app-at-test-network:
        aliases:
          - fast.api.frank
  slow-api:
    build: ./api
    ports:
      - '8001:80'
    entrypoint:
      - npm
      - start
      - '--'
      - '3000'
    networks:
      one-app-at-test-network:
        aliases:
          - slow.api.frank
  extra-slow-api:
    build: ./api
    ports:
      - '8002:80'
    entrypoint:
      - npm
      - start
      - '--'
      - '8000'
    networks:
      one-app-at-test-network:
        aliases:
          - extra-slow.api.frank
  nginx:
    image: 'nginx:1.17.5-alpine'
    volumes:
      - './nginx/default.conf:/etc/nginx/conf.d/default.conf'
      - './nginx/nginx-cert.pem:/etc/ssl/nginx-cert.pem'
      - './nginx/nginx-privkey.pem:/etc/ssl/nginx-privkey.pem'
      - './nginx/origin-statics:/usr/share/nginx/html'
    networks:
      one-app-at-test-network:
        aliases:
          - sample-cdn.frank
  selenium-chrome:
    image: >-
      selenium/standalone-chrome-debug@sha256:e8bf805eca673e6788fb50249b105be860d991ee0fa3696422b4cb92acb5c07a
    volumes:
      - '/dev/shm:/dev/shm'
    ports:
      - '60041:4444'
    networks:
      one-app-at-test-network: null
